### ISSUE TITLE
Recieve email issue

### ISSUE THREAD

**Issue by 710krypto** [paolodaniele/portech#1]
Hello, 

I have been testing your code and I seem to get the sms to get through but I am also having problem with getting the emails to myself. I hope you could help me out.

Do I need to add SMTP to the code for it to work?

Please let me know.

Sincerely, 

Jermy Kock

**Comment by paolodaniele** [comment]
Hi,
this script work with sample anda basic mail() php function.
Actually it's not suggested to use this and some servers deny and block this function, so you can use PhpMailer or Swift to send email back to you with external SMTP.
Regards,
Paolo

**Comment by 710krypto** [comment]
Hello again, 

Thanks for the quick response. I wanted to ask if I could contact you privately for project?

Please let me know.

Sincerely,

Jermy Kock

**Comment by paolodaniele** [comment]
Hi,
you can reach me from my website www.paolodaniele.it
Regards,
P

**Comment by 710krypto** [comment]
Hello again, 

I just sent you an email. 

Let me know if you receive it.

Best regards, 

Jermy Kock
